### ISSUE TITLE
Documentation TODO

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#1010]
+ [ ] https://github.com/vincentarelbundock/marginaleffects/issues/990
+ [ ] https://github.com/vincentarelbundock/marginaleffects/issues/977
+ [ ] https://github.com/vincentarelbundock/marginaleffects/issues/972
+ [ ] https://github.com/vincentarelbundock/marginaleffects/issues/962 with this issue in mind:https://github.com/vincentarelbundock/marginaleffects/issues/1097
+ [ ] https://github.com/vincentarelbundock/marginaleffects/issues/914
